//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// https://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html

// 
//This source code was auto-generated by MonoXSD
//
using System.Collections.Generic;

namespace UnityEditor.Localization.Plugins.XLIFF.V20
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class xliff
    {
        private List<file> fileField = new List<file>();

        private string versionField;

        private string srcLangField;

        private string trgLangField;

        private string spaceField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file")]
        public List<file> file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string srcLang
        {
            get
            {
                return this.srcLangField;
            }
            set
            {
                this.srcLangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trgLang
        {
            get
            {
                return this.trgLangField;
            }
            set
            {
                this.trgLangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class file
    {
        private skeleton skeletonField;

        private System.Xml.XmlElement[] anyField;

        private List<note> notesField;

        private List<object> itemsField = new List<object>();

        private string idField;

        private yesNo canResegmentField;

        private string originalField;

        private yesNo translateField;

        private dirValue srcDirField;

        private dirValue trgDirField;

        private string spaceField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public file()
        {
            this.canResegmentField = yesNo.yes;
            this.translateField = yesNo.yes;
            this.srcDirField = dirValue.auto;
            this.trgDirField = dirValue.auto;
        }

        /// <remarks/>
        public skeleton skeleton
        {
            get
            {
                return this.skeletonField;
            }
            set
            {
                this.skeletonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable = false)]
        public List<note> notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group", typeof(group))]
        [System.Xml.Serialization.XmlElementAttribute("unit", typeof(unit))]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canResegment
        {
            get
            {
                return this.canResegmentField;
            }
            set
            {
                this.canResegmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string original
        {
            get
            {
                return this.originalField;
            }
            set
            {
                this.originalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(dirValue.auto)]
        public dirValue srcDir
        {
            get
            {
                return this.srcDirField;
            }
            set
            {
                this.srcDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(dirValue.auto)]
        public dirValue trgDir
        {
            get
            {
                return this.trgDirField;
            }
            set
            {
                this.trgDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class skeleton
    {

        private System.Xml.XmlNode[] anyField;

        private string hrefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class note
    {

        private string idField;

        private appliesTo appliesToField;

        private bool appliesToFieldSpecified;

        private string categoryField;

        private string priorityField;

        private System.Xml.XmlAttribute[] anyAttrField;

        private string[] textField;

        public note()
        {
            this.priorityField = "1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public appliesTo appliesTo
        {
            get
            {
                return this.appliesToField;
            }
            set
            {
                this.appliesToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appliesToSpecified
        {
            get
            {
                return this.appliesToFieldSpecified;
            }
            set
            {
                this.appliesToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum appliesTo
    {

        /// <remarks/>
        source,

        /// <remarks/>
        target,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class group
    {
        private System.Xml.XmlElement[] anyField;

        private List<note> notesField;

        private List<object> itemsField = new List<object>();

        private string idField;

        private string nameField;

        private yesNo canResegmentField;

        private bool canResegmentFieldSpecified;

        private yesNo translateField;

        private bool translateFieldSpecified;

        private dirValue srcDirField;

        private bool srcDirFieldSpecified;

        private dirValue trgDirField;

        private bool trgDirFieldSpecified;

        private string typeField;

        private string spaceField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable = false)]
        public List<note> notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group", typeof(group))]
        [System.Xml.Serialization.XmlElementAttribute("unit", typeof(unit))]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo canResegment
        {
            get
            {
                return this.canResegmentField;
            }
            set
            {
                this.canResegmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canResegmentSpecified
        {
            get
            {
                return this.canResegmentFieldSpecified;
            }
            set
            {
                this.canResegmentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool translateSpecified
        {
            get
            {
                return this.translateFieldSpecified;
            }
            set
            {
                this.translateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue srcDir
        {
            get
            {
                return this.srcDirField;
            }
            set
            {
                this.srcDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool srcDirSpecified
        {
            get
            {
                return this.srcDirFieldSpecified;
            }
            set
            {
                this.srcDirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue trgDir
        {
            get
            {
                return this.trgDirField;
            }
            set
            {
                this.trgDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trgDirSpecified
        {
            get
            {
                return this.trgDirFieldSpecified;
            }
            set
            {
                this.trgDirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class unit
    {

        private System.Xml.XmlElement[] anyField;

        private List<note> notesField;

        private data[] originalDataField;

        private object[] itemsField;

        private string idField;

        private string nameField;

        private yesNo canResegmentField;

        private bool canResegmentFieldSpecified;

        private yesNo translateField;

        private bool translateFieldSpecified;

        private dirValue srcDirField;

        private bool srcDirFieldSpecified;

        private dirValue trgDirField;

        private bool trgDirFieldSpecified;

        private string spaceField = "preserve";

        private string typeField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("note", IsNullable = false)]
        public List<note> notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("data", IsNullable = false)]
        public data[] originalData
        {
            get
            {
                return this.originalDataField;
            }
            set
            {
                this.originalDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ignorable", typeof(ignorable))]
        [System.Xml.Serialization.XmlElementAttribute("segment", typeof(segment))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo canResegment
        {
            get
            {
                return this.canResegmentField;
            }
            set
            {
                this.canResegmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canResegmentSpecified
        {
            get
            {
                return this.canResegmentFieldSpecified;
            }
            set
            {
                this.canResegmentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool translateSpecified
        {
            get
            {
                return this.translateFieldSpecified;
            }
            set
            {
                this.translateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue srcDir
        {
            get
            {
                return this.srcDirField;
            }
            set
            {
                this.srcDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool srcDirSpecified
        {
            get
            {
                return this.srcDirFieldSpecified;
            }
            set
            {
                this.srcDirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue trgDir
        {
            get
            {
                return this.trgDirField;
            }
            set
            {
                this.trgDirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool trgDirSpecified
        {
            get
            {
                return this.trgDirFieldSpecified;
            }
            set
            {
                this.trgDirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class data
    {

        private cp[] cpField;

        private string[] textField;

        private string idField;

        private dirValue dirField;

        private string spaceField;

        public data()
        {
            this.dirField = dirValue.auto;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cp")]
        public cp[] cp
        {
            get
            {
                return this.cpField;
            }
            set
            {
                this.cpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(dirValue.auto)]
        public dirValue dir
        {
            get
            {
                return this.dirField;
            }
            set
            {
                this.dirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class cp
    {

        private byte[] hexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
        public byte[] hex
        {
            get
            {
                return this.hexField;
            }
            set
            {
                this.hexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum dirValue
    {

        /// <remarks/>
        ltr,

        /// <remarks/>
        rtl,

        /// <remarks/>
        auto,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class ignorable
    {

        private source sourceField;

        private target targetField;

        private string idField;

        /// <remarks/>
        public source source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public target target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class source
    {

        private object[] itemsField;

        private string[] textField;

        private string langField;

        private string spaceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cp", typeof(cp))]
        [System.Xml.Serialization.XmlElementAttribute("ec", typeof(ec))]
        [System.Xml.Serialization.XmlElementAttribute("em", typeof(em))]
        [System.Xml.Serialization.XmlElementAttribute("mrk", typeof(mrk))]
        [System.Xml.Serialization.XmlElementAttribute("pc", typeof(pc))]
        [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
        [System.Xml.Serialization.XmlElementAttribute("sc", typeof(sc))]
        [System.Xml.Serialization.XmlElementAttribute("sm", typeof(sm))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class ec
    {

        private yesNo canCopyField;

        private yesNo canDeleteField;

        private yesNo canOverlapField;

        private yesNoFirstNo canReorderField;

        private string copyOfField;

        private string dataRefField;

        private dirValue dirField;

        private bool dirFieldSpecified;

        private string dispField;

        private string equivField;

        private string idField;

        private yesNo isolatedField;

        private string startRefField;

        private string subFlowsField;

        private string subTypeField;

        private attrType_type typeField;

        private bool typeFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        public ec()
        {
            this.canCopyField = yesNo.yes;
            this.canDeleteField = yesNo.yes;
            this.canOverlapField = yesNo.yes;
            this.canReorderField = yesNoFirstNo.yes;
            this.isolatedField = yesNo.no;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canCopy
        {
            get
            {
                return this.canCopyField;
            }
            set
            {
                this.canCopyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canDelete
        {
            get
            {
                return this.canDeleteField;
            }
            set
            {
                this.canDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canOverlap
        {
            get
            {
                return this.canOverlapField;
            }
            set
            {
                this.canOverlapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNoFirstNo.yes)]
        public yesNoFirstNo canReorder
        {
            get
            {
                return this.canReorderField;
            }
            set
            {
                this.canReorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string copyOf
        {
            get
            {
                return this.copyOfField;
            }
            set
            {
                this.copyOfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string dataRef
        {
            get
            {
                return this.dataRefField;
            }
            set
            {
                this.dataRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue dir
        {
            get
            {
                return this.dirField;
            }
            set
            {
                this.dirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dirSpecified
        {
            get
            {
                return this.dirFieldSpecified;
            }
            set
            {
                this.dirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disp
        {
            get
            {
                return this.dispField;
            }
            set
            {
                this.dispField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string equiv
        {
            get
            {
                return this.equivField;
            }
            set
            {
                this.equivField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.no)]
        public yesNo isolated
        {
            get
            {
                return this.isolatedField;
            }
            set
            {
                this.isolatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string startRef
        {
            get
            {
                return this.startRefField;
            }
            set
            {
                this.startRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKENS")]
        public string subFlows
        {
            get
            {
                return this.subFlowsField;
            }
            set
            {
                this.subFlowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attrType_type type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum yesNo
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum yesNoFirstNo
    {

        /// <remarks/>
        yes,

        /// <remarks/>
        firstNo,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum attrType_type
    {

        /// <remarks/>
        fmt,

        /// <remarks/>
        ui,

        /// <remarks/>
        quote,

        /// <remarks/>
        link,

        /// <remarks/>
        image,

        /// <remarks/>
        other,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class em
    {

        private string startRefField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string startRef
        {
            get
            {
                return this.startRefField;
            }
            set
            {
                this.startRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class mrk
    {

        private object[] itemsField;

        private string[] textField;

        private string idField;

        private yesNo translateField;

        private bool translateFieldSpecified;

        private string typeField;

        private string refField;

        private string valueField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cp", typeof(cp))]
        [System.Xml.Serialization.XmlElementAttribute("ec", typeof(ec))]
        [System.Xml.Serialization.XmlElementAttribute("em", typeof(em))]
        [System.Xml.Serialization.XmlElementAttribute("mrk", typeof(mrk))]
        [System.Xml.Serialization.XmlElementAttribute("pc", typeof(pc))]
        [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
        [System.Xml.Serialization.XmlElementAttribute("sc", typeof(sc))]
        [System.Xml.Serialization.XmlElementAttribute("sm", typeof(sm))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool translateSpecified
        {
            get
            {
                return this.translateFieldSpecified;
            }
            set
            {
                this.translateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class pc
    {

        private object[] itemsField;

        private string[] textField;

        private yesNo canCopyField;

        private yesNo canDeleteField;

        private yesNo canOverlapField;

        private bool canOverlapFieldSpecified;

        private yesNoFirstNo canReorderField;

        private string copyOfField;

        private string dispEndField;

        private string dispStartField;

        private string equivEndField;

        private string equivStartField;

        private string idField;

        private string dataRefEndField;

        private string dataRefStartField;

        private string subFlowsEndField;

        private string subFlowsStartField;

        private string subTypeField;

        private attrType_type typeField;

        private bool typeFieldSpecified;

        private dirValue dirField;

        private bool dirFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        public pc()
        {
            this.canCopyField = yesNo.yes;
            this.canDeleteField = yesNo.yes;
            this.canReorderField = yesNoFirstNo.yes;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cp", typeof(cp))]
        [System.Xml.Serialization.XmlElementAttribute("ec", typeof(ec))]
        [System.Xml.Serialization.XmlElementAttribute("em", typeof(em))]
        [System.Xml.Serialization.XmlElementAttribute("mrk", typeof(mrk))]
        [System.Xml.Serialization.XmlElementAttribute("pc", typeof(pc))]
        [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
        [System.Xml.Serialization.XmlElementAttribute("sc", typeof(sc))]
        [System.Xml.Serialization.XmlElementAttribute("sm", typeof(sm))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canCopy
        {
            get
            {
                return this.canCopyField;
            }
            set
            {
                this.canCopyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canDelete
        {
            get
            {
                return this.canDeleteField;
            }
            set
            {
                this.canDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo canOverlap
        {
            get
            {
                return this.canOverlapField;
            }
            set
            {
                this.canOverlapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canOverlapSpecified
        {
            get
            {
                return this.canOverlapFieldSpecified;
            }
            set
            {
                this.canOverlapFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNoFirstNo.yes)]
        public yesNoFirstNo canReorder
        {
            get
            {
                return this.canReorderField;
            }
            set
            {
                this.canReorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string copyOf
        {
            get
            {
                return this.copyOfField;
            }
            set
            {
                this.copyOfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispEnd
        {
            get
            {
                return this.dispEndField;
            }
            set
            {
                this.dispEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispStart
        {
            get
            {
                return this.dispStartField;
            }
            set
            {
                this.dispStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string equivEnd
        {
            get
            {
                return this.equivEndField;
            }
            set
            {
                this.equivEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string equivStart
        {
            get
            {
                return this.equivStartField;
            }
            set
            {
                this.equivStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string dataRefEnd
        {
            get
            {
                return this.dataRefEndField;
            }
            set
            {
                this.dataRefEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string dataRefStart
        {
            get
            {
                return this.dataRefStartField;
            }
            set
            {
                this.dataRefStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKENS")]
        public string subFlowsEnd
        {
            get
            {
                return this.subFlowsEndField;
            }
            set
            {
                this.subFlowsEndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKENS")]
        public string subFlowsStart
        {
            get
            {
                return this.subFlowsStartField;
            }
            set
            {
                this.subFlowsStartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attrType_type type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue dir
        {
            get
            {
                return this.dirField;
            }
            set
            {
                this.dirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dirSpecified
        {
            get
            {
                return this.dirFieldSpecified;
            }
            set
            {
                this.dirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class ph
    {

        private yesNo canCopyField;

        private yesNo canDeleteField;

        private yesNoFirstNo canReorderField;

        private string copyOfField;

        private string dispField;

        private string equivField;

        private string idField;

        private string dataRefField;

        private string subFlowsField;

        private string subTypeField;

        private attrType_type typeField;

        private bool typeFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        public ph()
        {
            this.canCopyField = yesNo.yes;
            this.canDeleteField = yesNo.yes;
            this.canReorderField = yesNoFirstNo.yes;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canCopy
        {
            get
            {
                return this.canCopyField;
            }
            set
            {
                this.canCopyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canDelete
        {
            get
            {
                return this.canDeleteField;
            }
            set
            {
                this.canDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNoFirstNo.yes)]
        public yesNoFirstNo canReorder
        {
            get
            {
                return this.canReorderField;
            }
            set
            {
                this.canReorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string copyOf
        {
            get
            {
                return this.copyOfField;
            }
            set
            {
                this.copyOfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disp
        {
            get
            {
                return this.dispField;
            }
            set
            {
                this.dispField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string equiv
        {
            get
            {
                return this.equivField;
            }
            set
            {
                this.equivField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string dataRef
        {
            get
            {
                return this.dataRefField;
            }
            set
            {
                this.dataRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKENS")]
        public string subFlows
        {
            get
            {
                return this.subFlowsField;
            }
            set
            {
                this.subFlowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attrType_type type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class sc
    {

        private yesNo canCopyField;

        private yesNo canDeleteField;

        private yesNo canOverlapField;

        private yesNoFirstNo canReorderField;

        private string copyOfField;

        private string dataRefField;

        private dirValue dirField;

        private bool dirFieldSpecified;

        private string dispField;

        private string equivField;

        private string idField;

        private yesNo isolatedField;

        private string subFlowsField;

        private string subTypeField;

        private attrType_type typeField;

        private bool typeFieldSpecified;

        private System.Xml.XmlAttribute[] anyAttrField;

        public sc()
        {
            this.canCopyField = yesNo.yes;
            this.canDeleteField = yesNo.yes;
            this.canOverlapField = yesNo.yes;
            this.canReorderField = yesNoFirstNo.yes;
            this.isolatedField = yesNo.no;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canCopy
        {
            get
            {
                return this.canCopyField;
            }
            set
            {
                this.canCopyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canDelete
        {
            get
            {
                return this.canDeleteField;
            }
            set
            {
                this.canDeleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.yes)]
        public yesNo canOverlap
        {
            get
            {
                return this.canOverlapField;
            }
            set
            {
                this.canOverlapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNoFirstNo.yes)]
        public yesNoFirstNo canReorder
        {
            get
            {
                return this.canReorderField;
            }
            set
            {
                this.canReorderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string copyOf
        {
            get
            {
                return this.copyOfField;
            }
            set
            {
                this.copyOfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string dataRef
        {
            get
            {
                return this.dataRefField;
            }
            set
            {
                this.dataRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dirValue dir
        {
            get
            {
                return this.dirField;
            }
            set
            {
                this.dirField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dirSpecified
        {
            get
            {
                return this.dirFieldSpecified;
            }
            set
            {
                this.dirFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disp
        {
            get
            {
                return this.dispField;
            }
            set
            {
                this.dispField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string equiv
        {
            get
            {
                return this.equivField;
            }
            set
            {
                this.equivField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(yesNo.no)]
        public yesNo isolated
        {
            get
            {
                return this.isolatedField;
            }
            set
            {
                this.isolatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKENS")]
        public string subFlows
        {
            get
            {
                return this.subFlowsField;
            }
            set
            {
                this.subFlowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attrType_type type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class sm
    {

        private string idField;

        private yesNo translateField;

        private bool translateFieldSpecified;

        private string typeField;

        private string refField;

        private string valueField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo translate
        {
            get
            {
                return this.translateField;
            }
            set
            {
                this.translateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool translateSpecified
        {
            get
            {
                return this.translateFieldSpecified;
            }
            set
            {
                this.translateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class target
    {

        private object[] itemsField;

        private string[] textField;

        private string langField;

        private string spaceField;

        private string orderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cp", typeof(cp))]
        [System.Xml.Serialization.XmlElementAttribute("ec", typeof(ec))]
        [System.Xml.Serialization.XmlElementAttribute("em", typeof(em))]
        [System.Xml.Serialization.XmlElementAttribute("mrk", typeof(mrk))]
        [System.Xml.Serialization.XmlElementAttribute("pc", typeof(pc))]
        [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
        [System.Xml.Serialization.XmlElementAttribute("sc", typeof(sc))]
        [System.Xml.Serialization.XmlElementAttribute("sm", typeof(sm))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class segment
    {

        private source sourceField;

        private target targetField;

        private string idField;

        private yesNo canResegmentField;

        private bool canResegmentFieldSpecified;

        private stateType stateField;

        private string subStateField;

        public segment()
        {
            this.stateField = stateType.initial;
        }

        /// <remarks/>
        public source source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        public target target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public yesNo canResegment
        {
            get
            {
                return this.canResegmentField;
            }
            set
            {
                this.canResegmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canResegmentSpecified
        {
            get
            {
                return this.canResegmentFieldSpecified;
            }
            set
            {
                this.canResegmentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(stateType.initial)]
        public stateType state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subState
        {
            get
            {
                return this.subStateField;
            }
            set
            {
                this.subStateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    public enum stateType
    {

        /// <remarks/>
        initial,

        /// <remarks/>
        translated,

        /// <remarks/>
        reviewed,

        /// <remarks/>
        final,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class notes
    {

        private note[] noteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note")]
        public note[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:oasis:names:tc:xliff:document:2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:oasis:names:tc:xliff:document:2.0", IsNullable = false)]
    public partial class originalData
    {

        private data[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public data[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
}
